### ISSUE TITLE
[求指教] hev -> xray 不通

### ISSUE THREAD

**Issue by syf-work** [daemooon/Mango#32]
iOS TunnelProviderExtension

hev 配置：

```yml
tunnel:
  mtu: 9000

socks5:
  port: 7890
  address: ::1
  udp: 'udp'

misc:
  task-stack-size: 20480
  connect-timeout: 5000
  read-write-timeout: 60000
  log-file: stderr
  log-level: debug
  limit-nofile: 65535
```

先启动 xray， inbounds 有 socks (127.0.0.1:7890)，然后按照上述配置启动 hev，发现两者流量不通，我在 hev 和 xray 上都打了 log, 都能看到  xray 和 hev 的正常启动日志了，但是数据包，在 xray 那边没收到，有什么好的思路和坑吗？求大神指教
